apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "golang-mathapp.fullname" . }}
  labels:
    {{- include "golang-mathapp.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "golang-mathapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: golang-mathapp-tls
