apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-mathapp-pvc
  labels:
    {{- include "golang-mathapp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
