apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-mathapp.fullname" . }}
  labels:
    {{- include "golang-mathapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8010
  selector:
    {{- include "golang-mathapp.selectorLabels" . | nindent 4 }}
