# values.yaml
replicaCount: 3
image:
  repository: ahmedhajji1/golang-mathapp
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8010
ingress:
  enabled: true
  hostname: ahmedhajji-math.horizon-workspaces.com
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: gp2
serviceAccount:
  create: true
  name: my-serviceaccount
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

